### ISSUE TITLE
[1.7.10] Bypass advanced crafting recipes with BoP materials

### ISSUE THREAD

**Issue by syndicate25** [Leviathan143/betterbeginnings-MODIFIED#13]
Advanced crafting can be bypassed completely when using any wood type from Biomes O' Plenty.

A few things I tested were doors, fence gates, and chests. All can be made in the better beginnings double workbench/table, without putting the materials in on the left side. They show that they're required, but they aren't. They still are required when using any vanilla wood, though.

**Comment by Leviathan143** [comment]
I can't reproduce this in dev after the new changes. I don't remember trying before the changes, but this bug seems to be gone either way.
