### ISSUE TITLE
[1.10.2] Better Beginnings just crashes

### ISSUE THREAD

**Issue by kaperios** [Leviathan143/betterbeginnings-MODIFIED#14]
Minecraft version: 1.10.2
Forge version: 12.18.3.2221
Better Beginnings version: b0.9.8-R2c
(I tested it without any other mods)
http://pastebin.com/irJuve9n

**Comment by Leviathan143** [comment]
The crash log would be helpful...

**Comment by kaperios** [comment]
I deleted it by accident sorry

**Comment by Leviathan143** [comment]
Have you modified any recipes using the JSON configs?

**Comment by kaperios** [comment]
Nope

**Comment by Leviathan143** [comment]
Delete them then. Something's gone wrong when generating them, deleting them will cause them to be regenerated.

**Comment by kaperios** [comment]
Thanks it works!

**Comment by kaperios** [comment]
Thanks it works!
