### ISSUE TITLE
Crash while picking up Kiln [b0.9.8 R2c]

### ISSUE THREAD

**Issue by Leviathan143** [Leviathan143/betterbeginnings-MODIFIED#15]
Moved from einsteinsci/betterbeginnings#144
> Looks like a tile freak-out with the Kiln. I noticed it when crafting one to place, picking one up, and when breaking a kiln.
> 
> Absolutely loving this mod on 1.10.2 btw. Been working on a private pack centered on hardcore survival and this fits perfectly. Thank you for taking the time to create BB.
> 
> Forge: 1.10.2-12.18.3.2185
Minecraft Version: 1.10.2
Operating System: Linux (amd64) version 3.16.0-4-amd64
Java Version: 1.8.0_111, Oracle Corporation
> 
> http://pastebin.com/3tBtzkWn

**Comment by Leviathan143** [comment]
Looks like an issue with Tough As Nails. They assume that the metadata of ItemBlocks corresponds directly to the metadata of the corresponding block. The furnace blocks use metadata to save their orientation. This data does not transfer to the ItemBlock form, so it always has a metadata of 0. 0 corresponds to EnumFacing.UP, which is not a valid EnumFacing for the furnaces.

**Comment by Leviathan143** [comment]
OK, looking at the vanilla code this is actually an issue with BB. It seems ItemBlock meta must correspond to Block meta.

**Comment by buymytoasters** [comment]
Thank you Leviathan. Your work is much appreciated.
