### ISSUE TITLE
[1.7.10] Shift-clicking Harvestcraft Bakeware into BB Brick Oven results in crash

### ISSUE THREAD

**Issue by syndicate25** [Leviathan143/betterbeginnings-MODIFIED#16]
Tried making recipes for Harvestcraft items to include the Harvestcraft Bakeware, and have it reused or damaged after baking, using MineTweaker3. Shift-clicking the Harvestcraft Bakeware into the BB Brick Oven crashes the game.  It allows you to manually move the bakeware into the oven using left-click, but then will crash if you shift-click the rest of the ingredients into the oven while the bakeware also in the oven.

Crash report:
http://pastebin.com/ekJZVnR2

Scripts used:
http://pastebin.com/Jtd3M090

**Comment by Leviathan143** [comment]
The MT support backport from 1.10.2 seems to have fixed this :D. I'll release it soon, if you find that the bug is still present comment on this issue and I'll reopen it.
