### ISSUE TITLE
Enchantment Diffusion Issue

### ISSUE THREAD

**Issue by Gametron13** [Leviathan143/betterbeginnings-MODIFIED#18]
I am in the 1.10.2 version and the Enchantment Diffusion for the Infusion Repair Station isn't working. I put the cloth on the table, but when I dropped the tool and book I wanted to get the enchantment from, it didn't suck the items in like the guide said. Also, when I tried to get my piece of cloth back, it disappeared. I hope you can eventually fix this. 👍

**Comment by Leviathan143** [comment]
Please describe the **exact** series of steps required to reproduce this.

**Comment by Gametron13** [comment]
I don't really know what that means "reproduce." If you're asking me what I was wanting to do, I had a bow enchanted with Unbreaking III and I wanted to use it on something else. The mod guide says to place a piece of cloth on the Infusion repair table just like you would a tool and drop the enchanted item and a book onto the table and they would both be sucked in. I dropped both onto the table and they kept floating on the top and nothing happened since that.

**Comment by Leviathan143** [comment]
> I don't really know what that means "reproduce.

I want to know how I can recreate this bug myself. I just tested it and it worked fine.
I:
1. Right-clicked on the IRS with a piece of cloth in hand.
2. Dropped the enchanted tool on the table.
3. Dropped a book on the table(Enchanted Books or Book and Quills will not work).
4. Stood on the table while it drained the required health.

**Comment by Gametron13** [comment]
Let me try...

It still doesn't work for me. Maybe send me a video showing it working because I may be doing it wrong. I have a tendency to do that sometimes. :P

And I figured out the "not getting cloth back" issue. If I right click the table with an empty hand, I get it back but if it's not empty it disappears.

**Comment by Leviathan143** [comment]
Oh, it seems there is an issue. Apparently the IRS doesn't accept bows for some reason.

**Comment by Leviathan143** [comment]
I keep encountering bugs while trying to fix this. The IRS is way too buggy, I'm going to completely rewrite it.

**Comment by Gametron13** [comment]
I appreciate that. I want that Unbreaking III book! :P Thank you for your troubles. :)

**Comment by Leviathan143** [comment]
@Gametron13 
I've just pushed the last commit in the rework to the repo. It'll be in the next build

**Comment by Gametron13** [comment]
Yay! Thank you so much!!!
