### ISSUE TITLE
Conflict with Tough as Nails mod

### ISSUE THREAD

**Issue by reschnur** [Leviathan143/betterbeginnings-MODIFIED#19]
n the 1.10.2 version I am also using the Tough as Nails mod. TAN has a water bottle for thirst that must be cooked in a furnace so you can make juices.

None of the BB furnaces will not handle it and placing the bottle in one crashes the game.

I disabled the advanced furnace options and went back to the vanilla furnace and it works again, but I sure miss the challenges of the advanced furnaces.

Another thing that happened after I disabled the advanced furnaces was when I went back to the game and accessed the advanced furnaces or tried to break them to get rid of them the game crashes then to. Once the block is gone the game is fine.
[crash20170125.txt](https://github.com/Leviathan143/betterbeginnings-MODIFIED/files/731313/crash20170125.txt)

**Comment by Leviathan143** [comment]
> None of the BB furnaces will not handle it and placing the bottle in one crashes the game.

Crash report for this please.

**Comment by reschnur** [comment]
There are actually three stages: unfiltered, filtered, purified. You place the filtered version (Filtered Water Bottle item name in Minecraft) in a furnace and it cooks into the purified version which can then be used to brew juices.

Here are the crash reorts from three different steps. Each report has comments in the front I added to tell you what I did/was doing at the time of the crash.

Good hunting.

[BBCrash - 3.txt](https://github.com/Leviathan143/betterbeginnings-MODIFIED/files/736431/BBCrash.-.3.txt)
[BBCrash 1.txt](https://github.com/Leviathan143/betterbeginnings-MODIFIED/files/736433/BBCrash.1.txt)
[BBCrash - 2.txt](https://github.com/Leviathan143/betterbeginnings-MODIFIED/files/736432/BBCrash.-.2.txt)

**Comment by Leviathan143** [comment]
Thank you, that's very helpful. The crash when breaking the kiln is the same issue as #15 and has already been fixed. I'm currently trying to debug the other crash, but I'm being hampered by TAN refusing to load in my dev workspace.

**Comment by Leviathan143** [comment]
> None of the BB furnaces will handle it
BB's [JSON recipe system](https://github.com/einsteinsci/betterbeginnings/wiki/JSON-Recipes) allows you to add/modify/remove recipes. BB also has an auto json gen command, /jsongen. That doesn't work for every recipe, so you will have to add some recipes using the JSON recipe system. Improving the autoloader is on the todo list.
