### ISSUE TITLE
[1.10.2] Axe whitelist does not seem to work at all

### ISSUE THREAD

**Issue by al132** [Leviathan143/betterbeginnings-MODIFIED#23]
In the config file there is this bit about listing tools that should be treated as axes when seeing if a tool can harvest wood or not. It says "Use this format: 'modid:itemName=toolTier' [default: ]" but it doesn't seem to be working correctly as far as I can tell. I've made sure that the config file is reloaded, i've tried different harvest levels, anything I can think of but no luck.

[here is what it looks like in my config file](https://gist.github.com/al132/173d3157e9b21b0f238b746a4895453c)

Edit: using the most recent version on curse - betterbeginnings-MC1.10.2-b0.9.8-R2c
forge v2221

**Comment by Leviathan143** [comment]
I'll take a look. 

I need a bit more info though
Is the wood vanilla wood, or from a mod?
Do you have any other mods installed that modify block breaking mechanics?

**Comment by al132** [comment]
Ah, good call. I have [Harvest Tweaks](https://minecraft.curseforge.com/projects/harvest-tweaks) installed and it must override whatever is going on here. Fortunately, it lets me add items to a list of "axes" which fixed everything up. Sorry about the trouble.

**Comment by Leviathan143** [comment]
> Sorry about the trouble
@al132 It's no problem
