### ISSUE TITLE
Better building wands cross mod crash?

### ISSUE THREAD

**Issue by wizard1399** [Leviathan143/betterbeginnings-MODIFIED#24]
Hey, 
I think this is a cross mod crash related to better building wands. I think I had a builders wand in my hand and moused over the kiln to cause this crash. 

[crash-2017-02-06_19.57.36-client.txt](https://github.com/Leviathan143/betterbeginnings-MODIFIED/files/756383/crash-2017-02-06_19.57.36-client.txt)

**Comment by Leviathan143** [comment]
Same issue as #15. Already fixed

**Comment by wizard1399** [comment]
Pushed to curse forge yet? I have the most current according to what is publically available.

**Comment by Leviathan143** [comment]
No

**Comment by wizard1399** [comment]
Sad reality is that no one reads the change log unless it is for a version they just downloaded to see what changed.  You will probably continue to recieve bug reports until you publish to curseforge.
