### ISSUE TITLE
Compatibility Issue with Ars Magica 2

### ISSUE THREAD

**Issue by Spikeddragon** [Leviathan143/betterbeginnings-MODIFIED#28]
The dig spell in Ars Magica (both touch and projectile) do not drop blocks that BB makes unbreakable without the correct tool

Example:
Using a dig spell on an oak log doesn't drop the log (this also doesn't damage the player) but if
the spell is used on a modded tree that is breakable by hand, the log drops.

BetterBeginnings: b0.9.8-R4c

Forge: 12.18.3.2239

Minecraft: 1.10.2

**Comment by Leviathan143** [comment]
I've reproduced this and begun debugging it

**Comment by Leviathan143** [comment]
Seems this is an issue with Ars Magica 2. The spell items have no tool class, so BB sees them as invalid in this case. I'll create an issue or PR a fix in the morning.
