### ISSUE TITLE
Advanced Recipe  Table Loses Extra Material

### ISSUE THREAD

**Issue by reschnur** [Leviathan143/betterbeginnings-MODIFIED#29]
Please fill out **all** applicable sections in the template below:

**Description:**

Advanced crafting table does not recognize the need to output multiple increments of the item shown.

**Steps to reproduce:**

Placed 2 log blocks in advanced crafting table and only got 4 planks not 8 as expected and all of the logs disappeared (were consumed).

Same for planks to slabs, and fences and gates. I stopped trying after that. Tried single pick and shift-click with same results.

Doing them one-at-a-time works fine. Adding any extra material loses the extra material.

Standard crafting table works.

**Version Info(Exact versions only):**
BetterBeginnings: betterbeginnings-MC1.10.2-b0.9.8-R4c

Forge: 2185 with LiteLoader#9

Minecraft: 1.10.2

**Logs and other useful information:**

The install has a minimum of mods (map, hud). The only mod that I know of that adds blocks is wuest utilities.

**Comment by Leviathan143** [comment]
Thanks for the report.
I have been debugging and found that this bug seems to only occur with non-advanced recipes. Advanced recipes function correctly. I will update this post with more information as I find it.
