### ISSUE TITLE
Crafting conflict

### ISSUE THREAD

**Issue by wizard1399** [Leviathan143/betterbeginnings-MODIFIED#32]
Just wanted to let you know that there is a crafting conflict for your flint knife recipe with the mod BetterWithMods. BWM ads a sharpening kit which is crafted using 2 flint in a diagonal pattern in a 2 x 2 grid. Maybe you should add an alternate recipe that is vertical which only gets used if both mods are loaded?
Forge:

Minecraft:

**Logs and other useful information:**

**Comment by Leviathan143** [comment]
Nope. There a million little things like this, I can't fix them all. In this case you can fix it yourself using CraftTweaker.
