### ISSUE TITLE
Bone Pick does not follow config settings.

### ISSUE THREAD

**Issue by AnonTheMouse** [Leviathan143/betterbeginnings-MODIFIED#33]
Please fill out **all** applicable sections in the template below:

**Description:** When the configuration setting to use twine and string as tool bindings is turned on and the JSON file regenerated, the Bone Pickaxe will still require only leather strips.

**Steps to reproduce:** Turn on twine setting in config, regenerate JSON as instructed, attempt to craft Bone Pickaxe using twine.

**Comment by Leviathan143** [comment]
More serious than I thought. All recipes ignore this

**Comment by Leviathan143** [comment]
Sorry this took a while.
