### ISSUE TITLE
[Feature Request] Add minetweaker 1.10.2 support for being able to add/remove fuel sources for the campfire.

### ISSUE THREAD

**Issue by Titus-Armillius** [Leviathan143/betterbeginnings-MODIFIED#37]
**Description:**
I'm making a modpack for the RTG mod and I would like to add kindling as a fuel source for the campfire, as well as a few other materials. 

As a side note, from a realism-based perspective; it doesn't make much sense for the player to add large logs or planks as the fuel source for their campfire considering that the main structure already contains logs. In real life, sticks/twigs, kindling, etc. are used; especially on a campfire which is so small.

**Version Info(Exact versions only):**
BetterBeginnings: latest 1.10.2

Forge: latest 1.10.2

**Comment by Leviathan143** [comment]
I've been considering this anyway, now that I know someone wants it I'll put it higher up the TODO list.

>As a side note, from a realism-based perspective; it doesn't make much sense for the player to add large logs or planks as the fuel source for their campfire considering that the main structure already contains logs. In real life, sticks/twigs, kindling, etc. are used; especially on a campfire which is so small.

BB is not about realism. It is about extending earlygame in an enjoyable way that avoids grind.

**Comment by Leviathan143** [comment]
@Titus-Armillius A possible implementation of this is currently in testing. I thought you might like to know that.
