### ISSUE TITLE
flint hatchet durabililty

### ISSUE THREAD

**Issue by wizard1399** [Leviathan143/betterbeginnings-MODIFIED#38]
Please fill out **all** applicable sections in the template below:

**Description:**
When you use the flint hatchet you can use it till the durabililty says 0/max durability. The hatchet should break when it changes from 1 -> 0, not 0 -> (-1). I think this could be caused by calling the break event on the wrong durability.  When you use the hatchet when it has 0 durability, it breaks the block but does not give you the drop from it and the tool breaks. 

**Steps to reproduce:**
1. use a flint hatchet down to 0 durability. notice that it doesn't break yet
2. use the hatchet 1 more time. notice that it breaks the log, the tool breaks, and you don't get the drop.

**Version Info(Exact versions only):**
BetterBeginnings:  vers 1.10.2-b0.9.8-R5c
Forge:  12.18.3.2254
Minecraft: 1.10.2

**Logs and other useful information:**

**Comment by Leviathan143** [comment]
This is vanilla behaviour
