### ISSUE TITLE
[Suggestion] Kiln, Oven & Smelter in a Minecart

### ISSUE THREAD

**Issue by LordDan1989** [Leviathan143/betterbeginnings-MODIFIED#39]
As BB is practically a replacer for the Vanilla Furnace it would make sense to have a Minecart variant with both the Kiln and Smelter (Oven?) At the moment with BB installed I have no recipes to make a Furnace as the Furnace has no recipes except one last one, the Furnace in a Minecart. It is of course easy to change the recipe to accept the Kiln/Smelter, but it is still functionally a vanilla Furnace and will drop a Vanilla furnace when broken. I feel this is the last remaining piece for complete Furnace removal.

**Comment by Leviathan143** [comment]
Makes sense, I see no need for an Oven or Smelter in a Minecart though. A furnace minecart is just a coal/charcoal powered minecart, an Oven/Smelter in a Minecart would just be a visual variant

. I'll change the Furnace Minecart to be crafted with a kiln, drop a kiln and render a kiln inside it.
