### ISSUE TITLE
Campfire Won't Light

### ISSUE THREAD

**Issue by elwooha6** [Leviathan143/betterbeginnings-MODIFIED#40]
**Description:**
I can't get any campfire to light.

**Steps to reproduce:**
Craft a Fire Bow or Flint and Steel and right-click on an unlit campfire.

**Version Info(Exact versions only):**
BetterBeginnings: b0.9.8-R6c

Forge: 12.18.3.2281

Minecraft: 1.10.2

**Logs and other useful information:**
latest.log makes no mention of errors.

**Comment by Leviathan143** [comment]
It needs both fuel and something to process before it'll light.
