### ISSUE TITLE
MT Feature Request

### ISSUE THREAD

**Issue by elwooha6** [Leviathan143/betterbeginnings-MODIFIED#41]
**Description:**
I'd like to be able to set a specific cooking tool for the campfire. For example I want to be able to setup a recipe with MineTweaker to create Pams Harvestcraft biscuits with the campfire but I don't want it to be possible to use the rotisserie stick for this specific recipe. If possible I'd really like to be able to set any item:meta combination as a tool for the campfire but I'd settle for the first option of course.

**Comment by Leviathan143** [comment]
I would have to significantly rewrite the campfire recipe logic to do this. What exactly do you want to do and why?

**Comment by elwooha6** [comment]
The example given is pretty self explanatory but basically I would like more control over the campfire overall.

**Comment by Leviathan143** [comment]
> The example given is pretty self explanatory

Not really. You just said I want to do X. I want to know what X is in more detail and why you wish to do X.

**Comment by Leviathan143** [comment]
Closing due to lack of response and the technical difficulty of this. Implementing this suggestion would require rewriting a significant portion of the campfire recipe system. Hence I am not interested in doing this unless multiple people desire it.
