### ISSUE TITLE
AdvancedCrafting CraftTweaker removeOutput doesn't seem to work

### ISSUE THREAD

**Issue by davqvist** [Leviathan143/betterbeginnings-MODIFIED#42]
Please fill out **all** applicable sections in the template below:

**Description:**
AdvancedCrafting CraftTweaker removeOutput doesn't seem to work

**Steps to reproduce:**
First, is this the correct github? The einsteinsci one doesn't seem up-to-date, but is linked from curse while your wiki is linked from your curse as well. So I'm not sure. Anyway...

I'm currently evaluating this mod for my next modpack and tried to test the CraftTweaker integration.
So I tried removeOutput in the AdvancedCrafting and it gave me this error: 
https://pastebin.com/JQsYwD8t
This is my code `mods.betterbeginnings.AdvancedCrafting.removeOutput(<minecraft:chest>);`

removeRecipe worked then though, but it's of course a bit more cumbersome.

**Version Info(Exact versions only):**
BetterBeginnings: b0.9.8-R6c

Forge: 2281

Minecraft: 1.10.2

**Logs and other useful information:**

**Comment by Leviathan143** [comment]
Yes, this is the correct github. I've tried to change all the links to point here, but I don't have the required permissions to change all of them. When I joined the project, einsteinsci gave me limited permissions on the Curse project(I can change most things, however the source link is one of the things I can't change). When he went on indefinate hiatus, he did not give me any perms on the old repo, hence I could not maintain BB effectively there and I moved development here.

Thanks for your report.
