### ISSUE TITLE
Harvest Festival flower hurts

### ISSUE THREAD

**Issue by DcNdrew** [Leviathan143/betterbeginnings-MODIFIED#43]
Hi!
harvestfestival:flowers needs pickaxe, but it's a simple flower. How can I change that?

**Comment by wizard1399** [comment]
Try checking the config. I think there is an option in there to set blocks that should always be breakable. Add the harvest festival flowers to the list. This will probably require a minecraft restart so if you are playing on a server, this will require downtime.

**Comment by DcNdrew** [comment]
I tried, but doesn't work. Or I don't know... I just simply write between <> the "harvestrfestival:flowers", right?

**Comment by Leviathan143** [comment]
Yes

**Comment by DcNdrew** [comment]
I did that, but didn't work.

**Comment by Leviathan143** [comment]
Show the config

**Comment by Leviathan143** [comment]
Also post the log

**Comment by DcNdrew** [comment]
It works. I don't know what did I done different, but it works now, thanks!
