### ISSUE TITLE
CurseForge Cleanup.

### ISSUE THREAD

**Issue by Claycorp** [Leviathan143/betterbeginnings-MODIFIED#45]
You might want to clean up the CurseForge page for the mod as it has tons of info that is way outdated or not needed. Also have you tried to contact CurseForge to see if they will fix the perms on the mod page so you can update everything properly everything?

**Comment by Leviathan143** [comment]
> You might want to clean up the CurseForge page for the mod as it has tons of info that is way outdated or not needed.

Yeah, that's probably a good idea.

> Also have you tried to contact CurseForge to see if they will fix the perms on the mod page so you can update everything properly everything?

No, I'm not sure they'd do it while einsteinsci is still semi-active. It's been about 2.5 months since he was last active. I might try it if he stays inactive for much longer though.

**Comment by Leviathan143** [comment]
There, all cleaned up. I haven't contacted Curse about perms yet, but I'm thinking about doing in the near future.
