### ISSUE TITLE
Throwing knifes crash servers

### ISSUE THREAD

**Issue by Claycorp** [Leviathan143/betterbeginnings-MODIFIED#46]
**Description:**
Throw knife by clicking on a block and server crashes.
**Steps to reproduce:**
Hold knife. Throw knife.
**Version Info(Exact versions only):**
BetterBeginnings:

Forge:

Minecraft:

**Logs and other useful information:**
https://pastebin.com/JeQriPt3

**Comment by Leviathan143** [comment]
Apparently setVelocity() is client jar only for some reason. Mojang is weird.
