### ISSUE TITLE
Advanced crafting dupe bug.

### ISSUE THREAD

**Issue by Claycorp** [Leviathan143/betterbeginnings-MODIFIED#47]
**Description:**
Table dupes items along with all sorts of other funky stuff.
**Steps to reproduce:**
Will not post any information unless asked. Contact me on Twitch app (Claycorp) or Twitter (@Clay_corp) if you don't want this on git.
**Version Info(Exact versions only):**
BetterBeginnings: 0.9.8R6c
Forge: 2297
Minecraft:1.10.2

**Comment by Leviathan143** [comment]
Just post the info, I don't care if people know how to dupe stuff.

**Comment by Leviathan143** [comment]
Is this caused by shift-clicking the output slot?

**Comment by Claycorp** [comment]
Alright. How to do it.

1. Pick a recipe with more than 2 extra input items. (not sure if this is required or not)
2. Setup 3x3 grid with two crafts worth of items.
3. Place a single craft worth of one extra input. (The rest can be however many you want)
4. Craft one output. You should now be stuck with a grid full of empty item stacks.
5. Place items back into the item stacks (I did 4 for each one)
6. Refill Extra items and craft till extras run out. 3x3 won't be consumed and can be reclaimed.

This was done on a server thus i'm not sure if it works in single player. There was also some other odd behaviors with stacks doubling their self but i have yet to reproduce that. I do have screen shots of all of it.

**Comment by Claycorp** [comment]
Note: For step 5 if you do less than stacks of 4 it will consume down to two and then crafting again will put you at empty stacks. Anything over 4 in the stack sizes the stack is doubled per craft and can be reclaimed.

If you need anymore info I can reproduce it reliably on both infinite crafts and doubling.

**Comment by Claycorp** [comment]
Another bit of information. If you can somehow craft the stacks to overflow you will end up with negative items in a stack and those can be freely dragged around the inventory to make more blocks.

**Comment by Claycorp** [comment]
Just wondering when the next update is coming out. I'm working on a pack that has this mod in it and really don't want to start opening it up to more people till this and the server crashes from thrown knives is fixed.

**Comment by Leviathan143** [comment]
@Claycorp I have been thinking I should do a build. I feel there's enough done since the last build to release another, plus it's been a while since the last one. I'll make a build this evening.

**Comment by Claycorp** [comment]
How goes that new build?

**Comment by Leviathan143** [comment]
It's been submitted to CF.
