### ISSUE TITLE
Minetweaker can't remove all recipes from ovens.

### ISSUE THREAD

**Issue by Claycorp** [Leviathan143/betterbeginnings-MODIFIED#50]
Please fill out **all** applicable sections in the template below:

**Description:**
Cant remove Bread, Cookies or Marshmallows from oven with MineTweaker.

**Steps to reproduce:**
`Oven.removeOutput(<minecraft:bread>);` (for each one)  and the recipe stays.

**Version Info(Exact versions only):**
BetterBeginnings: B0.9.8-R6D

Forge: 2297

Minecraft: 1.10.2

**Logs and other useful information:**
Everything but those three can be removed with MineTweaker. Not sure why that would be but going to try and remove it with the included recipe configs.

**Comment by Leviathan143** [comment]
`Oven.removeOutput()` is stack size sensitive. All those recipes output more than 1 item.

**Comment by Claycorp** [comment]
It really shouldn't be as that is the opposite of how vanilla MineTweaker works. Remove is remove regardless of stacksize. If people want to take out a certain recipe that is what shaped/shapeless are for.

Are there any more oddities I should know of? I'm going to update the wiki to reflect this as it currently doesn't mention this stuff.

**Comment by Leviathan143** [comment]
>It really shouldn't be as that is the opposite of how vanilla MineTweaker works.

I wasn't aware of that. I'll change it to be in line with that.

>Are there any more oddities I should know of?

If anything is not in line with the standards set by vanilla Minetweaker, please tell me and I'll change it so it conforms.

**Comment by Claycorp** [comment]
Thanks. I'll keep an eye out.
