### ISSUE TITLE
Campfire recipes duplicate.

### ISSUE THREAD

**Issue by Claycorp** [Leviathan143/betterbeginnings-MODIFIED#52]
**Description:**
Reloading with any campfire recipes will add the recipes without removing the old ones. Thus duplicating them. Restarting avoid this.

BetterBeginnings: B0.9.8-R6D

Forge: 2297

Minecraft: 1.10.2

**Comment by Leviathan143** [comment]
Version info please.

**Comment by Leviathan143** [comment]
Ugh, I dunno what's going on here. I tell JEI to remove the recipe, but it doesn't.
