### ISSUE TITLE
Can't remove charcoal from campfire.

### ISSUE THREAD

**Issue by Claycorp** [Leviathan143/betterbeginnings-MODIFIED#53]
**Description:**
`Campfire.removeOutput(<minecraft:coal:1>);` should remove the ability to make charcoal but it doesn't.

BetterBeginnings: B0.9.8-R6D

Forge: 2297

Minecraft: 1.10.2

**Comment by Leviathan143** [comment]
When reporting issues with MineTweaker compat, please provide minetweaker.log. Please also always fill out the version info section of the template.

**Comment by Leviathan143** [comment]
Thank you

**Comment by Claycorp** [comment]
This tied into #52 
Going to close it.

**Comment by Leviathan143** [comment]
Excellent.
