### ISSUE TITLE
Default beacon recipe is missing a texture.

### ISSUE THREAD

**Issue by Claycorp** [Leviathan143/betterbeginnings-MODIFIED#54]
**Description:**
The water bottle in the recipe has no texture.
http://i.imgur.com/teHOTCa.png

BetterBeginnings: B0.9.8-R6D

Forge: 2297

Minecraft: 1.10.2

**Comment by Leviathan143** [comment]
The issue here is that the awkward potion is missing NBT data. That's simple to fix. However the JSON recipe system doesn't support NBT. I'm trying to do that, but it's proving surprising difficult.
