### ISSUE TITLE
BetterBeginning's error loading 

### ISSUE THREAD

**Issue by Mysterizon** [Leviathan143/betterbeginnings-MODIFIED#57]
Please fill out **all** applicable sections in the template below:

**Description:**
I add around 50 mods along with Tough As Nail and Survivalist mod to Minecraft 1.10.2 so when Minecraft was starting up and loading mods and the mods are loading just fine until in Stage 4 (UCHI), <- the fourth letter is the stage 4, only BetterBeginning have shown an error in Stage 4. I have the report for you to take a look at. 

**Steps to reproduce:**

**Version Info(Exact versions only):**
**BetterBeginnings:** betterbeginnings-MC1.10.2-b0.9.8-R6d.jar

**Forge:** 12.18.3.2297

**Minecraft:**1.10.2

**Logs and other useful information:**
REPORT: https://pastebin.com/AX3uH4zZ

**Comment by Leviathan143** [comment]
Something is wrong with the [.json recipe files](https://github.com/Leviathan143/betterbeginnings-MODIFIED/wiki/JSON-Recipes). If you haven't modified them, just delete them and BB will regenerate them on next startup. If you have modified them, ensure that the registry names and other parameters are correct.
