### ISSUE TITLE
1.10.2 - Crash on startup

### ISSUE THREAD

**Issue by SirWindfield** [Leviathan143/betterbeginnings-MODIFIED#58]
**Description:**
Client crashes on startup.

**Version Info(Exact versions only):**
BetterBeginnings: b0.9.8-R6d

Forge: 12.18.3.2297

Minecraft: 1.10.2

**Logs and other useful information:**
[crash-report](https://gist.github.com/SirWindfield/446828a4b785ba1d78d031c5628e6d6a)
[log file](https://gist.github.com/SirWindfield/a2502f4d94c8904813ca297e986d7ed1)

**Comment by Leviathan143** [comment]
See #57.

**Comment by Leviathan143** [comment]
d3432f should make this much better.
