### ISSUE TITLE
Achievement chat hover is broken.

### ISSUE THREAD

**Issue by Claycorp** [Leviathan143/betterbeginnings-MODIFIED#61]
*Description:**
When hovering over an achievement you completed it should say what was completed. 
Like so: http://i.imgur.com/130bxBG.png
**Steps to reproduce:**
Complete an achievement, hover over the text for it and it says "Invalid statistic/achievement!"
**Version Info(Exact versions only):**
BetterBeginnings:  0.9.8 R6d
Forge: 2297

Minecraft: **Logs and other useful information:**

**Comment by Leviathan143** [comment]
? 
That's an Immersive Engineering achievement.

**Comment by Claycorp** [comment]
Yes. I was just using it as an example. See "Steps to reproduce"

**Comment by Leviathan143** [comment]
Have you reproduced this with only BB? Does removing BB fix the issue?

**Comment by Claycorp** [comment]
no your achievements are broke. Not other mods.

**Comment by Leviathan143** [comment]
I completed "Survival of the Fittest", "I'm a sapling, I'm a sapling..." and "The Tiny Axe". The descriptions showed up properly for all of them.

**Comment by Claycorp** [comment]
http://i.imgur.com/dk5fWx9.png

**Comment by Leviathan143** [comment]
Oops. I misread the issue, sorry. I can successfully reproduce this.
