### ISSUE TITLE
Minetweaker Kiln NPE 

### ISSUE THREAD

**Issue by Claycorp** [Leviathan143/betterbeginnings-MODIFIED#63]
**Description:**
https://pastebin.com/sNnXRGdC
**Steps to reproduce:**
https://pastebin.com/6xaJuDQs
**Version Info(Exact versions only):**
BetterBeginnings: r6d

Forge:2316

Minecraft: 1.102

**Comment by Leviathan143** [comment]
Attempting to remove all recipes outputting charcoal from the kiln (As that is the only line that could cause this crash) failed to reproduce this crash in dev and in 0.9.8-R6d.

**Comment by Claycorp** [comment]
It was a random screw-up from the reload command as it seems to work fine otherwise. I wouldn't worry about it.
