### ISSUE TITLE
[Request]Create zh_CN.lang

### ISSUE THREAD

**Issue by YiChenCraft** [Leviathan143/betterbeginnings-MODIFIED#67]
I have a lang, can you add it to your mod?
[zh_CN.zip](https://github.com/Leviathan143/betterbeginnings-MODIFIED/files/1119966/zh_CN.zip)
I really love your mod, it's a great work and, please, keep it.

**Comment by Leviathan143** [comment]
Thanks very much for the translation. I'll have a look at it and then stick it in the next release.
