### ISSUE TITLE
Other Mods Iron Nuggets not being consumed in the Adavanced Crafting Recipes

### ISSUE THREAD

**Issue by kclobo2003** [Leviathan143/betterbeginnings-MODIFIED#68]
Please fill out **all** applicable sections in the template below:

**Description:**
When crafting recipes that require Iron Nuggets, Tinkers Construct and Thaumcrafts Iron nuggets are not being consumed when the item is made. 

But I am not only using the Tinkers Construct mod, TConstruct-1.7.10-1.8.8.DEV.1486950.  I am also using IguanaTinkerTweaks-1.7.10-2.1.6 

Thaumcraft : Thaumcraft-1.7.10-4.2.3.5 

**Steps to reproduce:**
Make Thuamcraft, Tinkersconstruct Iron Nuggets and make an item that requires the Iron nuggets from those 2 mentioned mods. 

**Version Info(Exact versions only):**
BetterBeginnings: **betterbeginnings-MC1.7.10-b0.9.6-R1a**

Forge: 10.13.4.1614
Server: Thermos-1.7.10-1614-server
Minecraft: 1.7.10

**Logs and other useful information:**

**Comment by Leviathan143** [comment]
This is probably the 1.7.10 version of #11

**Comment by Leviathan143** [comment]
Thought I'd let you know that I haven't forgotten about this issue. I've been busy with other projects and real life exams.

**Comment by kclobo2003** [comment]
That is understandable! I'm going throuhg a lot right now as well! 

Thank you for checking in though! 

Awesome job and remmeber to breath and take it one day at time!

**Comment by Leviathan143** [comment]
Closed by 480ca7a6db99dec12e31d4984369b97a2ea69d9f
