### ISSUE TITLE
CraftTweaker integration fails to remove advanced crafting recipes for tools

### ISSUE THREAD

**Issue by Nathan22211** [Leviathan143/betterbeginnings-MODIFIED#73]
Please fill out **all** applicable sections in the template below:

**Description:**
when trying to remove crafting stone tools in advanced crafting it says it works but it still shows in JEI and you can still craft it

**Steps to reproduce:** write a craft tweaker script to remove a tool from advanced crafting

**Version Info(Exact versions only):**
BetterBeginnings:b0.9.8-R8c

Forge: 1.10.2 12.18.3.2422

Minecraft:1.10.2

**Logs and other useful information:**
mod list
TAN
survivalist
rice crafting table
realistic survival RRS
primal core
kewaii lib
JEI
craft tweaker
better beginnings

**Comment by Leviathan143** [comment]
Yeah, it looks like `AdvancedCrafting.removeRecipe()` is broken. I think I've spotted the bug already though, so it shouldn't take long to fix. `AdvancedCrafting.removeOutput()` works though, so you can use that instead.

**Comment by Leviathan143** [comment]
Post it then. The whole thing. Just mentioning the first error is useless and rather annoying.

**Comment by Nathan22211** [comment]
that's all I got from using AdvancedCrafting.removeOutput(). unless you mean a log?

**Comment by Leviathan143** [comment]
Post crafttweaker.log and your script

**Comment by Nathan22211** [comment]
ok here's what I have (might of messed up the ore driect)

import mods.betterbeginnings.AdvancedCrafting;

AdvancedCrafting.removeRecipe(<minecraft:stone_pickaxe>, [[<minecraft:stone>, <minecraft:stone>, <minecraft:stone>], [null, <minecraft:stick>, null], [null, <minecraft:stick, null]], [<ore:itemToughString>]);

**Comment by Nathan22211** [comment]
no clue where the craft tweaker log is

**Comment by Nathan22211** [comment]
ok I found it. but it says no errors

[INITIALIZATION][CLIENT][INFO] CraftTweaker: Building registry
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][CLIENT][INFO] Loading scripts
[SERVER_STARTED][CLIENT][INFO] Fixed the RecipeBook

**Comment by Leviathan143** [comment]
I want the script that is using removeOutput() instead. I know removeRecipe() doesn't work, and will fix it. However in my testing removeOutput() still worked as expected.

**Comment by Nathan22211** [comment]
well I found a workaround for this bug. I just take all of the advanced crafting recipes from the main.JSON

**Comment by Nathan22211** [comment]
I did removeOutput(<minecraft:stone_pickaxe>)

**Comment by Nathan22211** [comment]
also just curious. is there a 1.12.2 alpha build on like jekins or your goggle drive, mediafire or dropbox? i'd be willing to test it out

**Comment by Leviathan143** [comment]
@Nathan22211 No. BB is currently in maintenance mode. See [here](http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/wip-mods/2192122-betterbeginnings-mod-reborn?comment=838) for details. I have the beginnings of a 1.11 port somewhere, but I never started a port to 1.12.

**Comment by Leviathan143** [comment]
I haven't forgotten about this, but unfortunately I will be unable to do anything about it for another week.

**Comment by Leviathan143** [comment]
I've just gotten around to trying to fix this, and discovered that there is no issue whatsoever. All the ingredients used in the stone tool recipes are oredicted, so you must use oredict ingredients in the script.
